name: Step 2 # Commit a file

# Checks if the learner completed tasks for step 2.
# - Triggers when the user makes a push to the branch 'my-first-branch' and modifies the file 'PROFILE.md'.

on:
  push:
    branches:
      - "my-first-branch"
    paths:
      - "PROFILE.md"

permissions:
  contents: read
  actions: write
  issues: write

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.7.0

  post_next_step_content:
    name: Post next step content
    needs: [find_exercise]
    uses: ./.github/workflows/shared-post-step-content.yml
    with:
      issue-number: ${{ needs.find_exercise.outputs.issue-number }}
      step-file: ".github/steps/3-open-a-pull-request.md"
      next-step-number: "3"
      next-workflow-name: "Step 3"
      current-workflow-name: ${{ github.workflow }}
