name: Step 4 # Merge your pull request

# Checks if the learner completed tasks for step 4.
# - Triggers when the user merges the pull request.
# - If all checks pass, the workflow is disabled so it doesn't run again. As such, workflow status badge will change to green.

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write
  actions: write
  issues: write

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.7.0

  post_review_content:
    name: Post review content
    needs: [find_exercise]
    if: |
      !github.event.repository.is_template
    uses: ./.github/workflows/shared-post-step-content.yml
    with:
      issue-number: ${{ needs.find_exercise.outputs.issue-number }}
      step-file: ".github/steps/x-review.md"
      intro-template-file: "exercise-toolkit/markdown-templates/step-feedback/lesson-review.md"
      post-watching-for-progress: false
      current-workflow-name: ${{ github.workflow }}

  finish_exercise:
    name: Finish Exercise
    needs: [find_exercise, post_review_content]
    uses: skills/exercise-toolkit/.github/workflows/finish-exercise.yml@v0.7.0
    with:
      issue-url: ${{ needs.find_exercise.outputs.issue-url }}
      exercise-title: "Introduction to GitHub"
